DROP TABLE IF EXISTS Student;
CREATE TABLE Student AS
SELECT DISTINCT Id, Name FROM UNF;

ALTER TABLE Student ADD PRIMARY KEY(Id);
ALTER TABLE Student MODIFY Id INTEGER NOT NULL AUTO_INCREMENT;
--INSERT INTO Student(Name) VALUES ("Lionel Messi");
--INSERT INTO Student(Name) VALUES ("Eden Hazard");